# Generated by Django 5.1.2 on 2024-10-11 10:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug-имя товара')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='product_images/small', verbose_name='маленькое изображение')),
                ('image_medium', models.ImageField(upload_to='product_images/medium', verbose_name='среднее изображение')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='product_images/large', verbose_name='большое изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='цена товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
